version: '3.7'
services:
  app:
    entrypoint: .docker/exec_dev/entrypoint.sh
    build:
      context: .docker/exec_dev/
      dockerfile: Dockerfile
    container_name: father
    ports:
      - 5555:3333
    volumes:
      - .:/home/node/app
    depends_on:
      - postgres
    networks:
      - proxynet
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - proxynet
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: father
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - proxynet
networks:
  proxynet:
    name: custom_network
